chef_api_url:
  test: http://127.0.0.1:9292 # chef-sero started by `rackup`
  development: http://127.0.0.1:4000 # chef-zero started with `rspec`

chef_client_name:
  test: stickywicket 
  development: stickywicket

chef_client_key_path:
  test: spec/fixtures/.chef/stickywicket.pem 
  development: spec/fixtures/.chef/stickywicket.pem 

