chef_api_url:
  test: http://127.0.0.1:4000
  development: http://127.0.0.1:4000

chef_client_name:
  test: admin
  development: admin

chef_client_key_path:
  test: spec/fixtures/admin.pem 
  development: spec/fixtures/admin.pem 
